apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FHDAVz5U7jEzmppl77AoGkk=,iv:L9InpMGBXzh/XQ/wZdej5hE/yFP4T2ygVVBmIhyCzB8=,tag:z1PHPytFlgyx8TgxMHX/Hw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:mL/sGaY3cTVM1MvLQUUwVJxw8JpyQ3iQpbxFP7dWEwl6/52aFA==,iv:QLjyr1eFBmXVI+LU7/outnIT7B0MXU1bQtShFKCN8XI=,tag:y1I0BHG6eeahLWPi/FqOiA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:XwDVteXxON1nJZipfhCjbg3A,iv:GQYleRWq1Ib9LyDGY+2BkBXbG3pa1rmmcQw8ySE34d0=,tag:/oXuCwHQ3uIw1DZIwibwFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17k7yuv7n8cxc3pclft8p3dzyjdjcrztpyv746p2g7pkz3j2nr32qphqsxu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UXJqdEpUQm9kU3Mwdk5z
            NnZZSVpjOFN3ZFk5Vzk5NjlaR1I2WlBpY3pZCi8yZS9YazNPcytZS2QwLzZSeWZa
            S05DeVB6NDg5Q05tRnFZSThCeG9VZzAKLS0tIENhSUF1VGlNcTZEa3Z6SDVnZkVz
            bWpiekIwYU1ha2NLQUpDV2FjbkdLdTQKtlrPBZahaeu+ekHtIXEWSmuIR1U4eBfC
            2gBX3KTaZ1Fkrf4YQidEx2CyFyJUCOLOFrI0H6hQwAQcwMIH43lwwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-09T00:59:03Z"
    mac: ENC[AES256_GCM,data:5W2qFoHshAlryMhUZpP11+ctGYNiUzsRx/mvzD1aw662mzyGjqYlbtXXsApovfW3ghWRgLKbdoNxzmOSUPzJCFRF9JlneG8MmtdjOHYCDe6eWccqx89IEwULzR1NZtBfukThehuGdREn/EOUHzNe65C/zwhcD6fFhSvQOzf2Mic=,iv:3rtS55p0zaS65O3Tnoydkj15DXll+aFqjtfUWQsK1zM=,tag:Hcc+TJYCpyOumgFcCblSVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
