kind: ENC[AES256_GCM,data:E4qJIKPv,iv:fC1tIkW4hyBX6tJiWFv7H1VU6l49yWsanYvAAyYtjMc=,tag:4ubxASAUT84L9Mu5Ty3VCQ==,type:str]
ansible_user: null
ansible_become_pass: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17k7yuv7n8cxc3pclft8p3dzyjdjcrztpyv746p2g7pkz3j2nr32qphqsxu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdUdKK3pUdUJDOXE0VnBP
            dE9IQ0pmQ1JmaGVXRFZSYmcwNnpHd25rWkJjCkRRSU1ObStPaHFOT0RaWTFhSm9J
            Y0phTE1aYjdqOFVPYzZvWGs1VEYzUzQKLS0tIEVzaUkrQ2cyWHRTUjJZRk1SYXQ1
            bXhoWE9HMlpqMWdNTmRwZmhoOVJGcFUK/+e/E7fPyXiiW0bF9D4Xh0VJWAMiBnUh
            dDDpfPeCGVUa7K+vMyz560mBz7QWVwbcAcENVEZLGbXvjrK8epcqRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T11:00:13Z"
    mac: ENC[AES256_GCM,data:/6rUup9L1H38Hw+eX4gBQ2rTIsv7C9jI6EFwSa8V2+GVzDQQeu/pEKAwbQKyYJVfJECthG4yL5UFIhs2ZxGQsWyhbzr48jIvBg51mTPXAhZx1vctxtfAPCqUjKZ/LsU/ZMdZYE2TGtt/V32BZxJMFykfky9OUElAwDkTwYZ+bhg=,iv:RDk6QwoYSm2LpHddo2aNZhFiedjwmkv2t52xzG8dMfc=,tag:ej+slM5g4ZpeltEFnp24+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
