apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:iPxx7bD6iN1qa60SWrJpW2X67a6GxYFNmIbw2ZTm1EDXKUxVSANq/A==,iv:796sNaww4zyKDwN1l7aoeEy7/TBhQLn8uDhx6/KRf+4=,tag:1SbNRyMS2l2biISoXqWHmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1myzelwautwjuwe8e2gpy4wn69qxx84w9v47auc8e4afhwuaq2q0qv5eqc8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdFJaTDd6U1VlVUhzelov
            MnpVMDJRaXB5N3ZjQ05SdjhTcDVUOWthSmdjCjVPbDNNWVFrVU90MjlaVEEwcHRw
            RklsclBqVEpzZ3dHMUtScmVJc2VHODAKLS0tIDZQRUIxV1RwcURMMG9uc2tRSWIv
            TnhxV1RodjdpbDVwK25XNHFmb25ZckUKD4EjrAARLrbfkTIq/seW3TRYWpSRI+/1
            NlXlPddIMM1/IAKBpPfMvNJTHytUfYVpriJTc1vQNgGDbC/dxZWmcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T22:51:02Z"
    mac: ENC[AES256_GCM,data:4+q/k/fSvCGW4f3wrIht/1DsFep+MBHoLOnn29WMs3kLPFzkI8qNxfO3cTMcWHy1Zpab++o4OjuANXFhT6N0tzLpQ6B7Zppkh/CQ1sWCJCXAxeAJYBmUyYy48U47XmI/YeXhusSYgYF4DGPkN0H1RWkgxQgRuShnnwWbPJRlsxM=,iv:EkdHuUKBlElynPjdRZ63mRAg6tZcgF0M7LuFjfoNeJk=,tag:Dfkn3hOysTDIRbMfA1GLgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
