apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:WrO2fKAj3GURlVEbXihFWHG5MwmXYfNa7/0DNF+Jo/6k6NNyKA==,iv:Ub08nZiwktCpvFbxvxaeuSG3ZT5PlDbPDcMJPDUGuDc=,tag:AD01FrjQTPgSrD38W0THfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1myzelwautwjuwe8e2gpy4wn69qxx84w9v47auc8e4afhwuaq2q0qv5eqc8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeTIveExhZzFiZ2Q3WUhJ
            emg3VTJtUW5xbXZRcUJTSG9DZmxEV2d5NzNZCjJJNGQ5V0dYd3NSUER3d1QrOFdi
            NTFLTnNOcG0vL0EweHVDYUUxS21ja1UKLS0tIEY4TE1xc1VRS3VkN1FpMmxFdzF3
            NkxrTUpuR2Q2L2tlOE1nZk12NXRValkKynplLg8L3AgrdvwSALVWGveyR9W5Nr77
            FaeCV2jmbl4wI/Z0VexAhYzyHtQATjDeT45Q0K006TqaTNCCp22lFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-26T22:51:02Z"
    mac: ENC[AES256_GCM,data:bPA9AaU92Bz2tyW8ykX0kQacQYm5+BW2iYHyZGfuq2HIyxrZm9MdkgyjSkLLDFSm4ErzvRgRv8Qz4A1K+D04vhmgkXEhYaCEB/PdUOs8VtAmciF0Gdu7IFcTL/yWrvIBObEqdK+tiaTLh2jJJR3+ave0/NB5G63UFaF1xwAXjeY=,iv:DHjpCgouwsEKAPgSRpuonSHsHycY2AjhlbP3Hhvo6H4=,tag:bI6HYw+00fk64nOg6JhA7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
