apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:16HwfU7r9/HF6XsWVeY7qmg=,iv:agXpl2KEHw3eFINZXRYQFIhR0aVznw/YBgLnBy2GZPc=,tag:ukxAdwSxAMAwdQs67zsdBg==,type:str]
    api-key: ENC[AES256_GCM,data:u4GOmHTNHvnyb3qRD2iu71P/Gk6mxh6uffnrgL44S60vwBoooA==,iv:TciWKROIdu9Mycb/Y9f3u/LPHEj4CLXTrQr8P1PBt+w=,tag:9ex+mfZDhzDe3mzBIDDjMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17k7yuv7n8cxc3pclft8p3dzyjdjcrztpyv746p2g7pkz3j2nr32qphqsxu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdit6T3BJUUx2K2djaWtv
            YnJQeWcxbGZqRVY4UjFhMmhWQ3lsK1R0SkdFClgrQ1B3L1Y1OW11aFlaV2g0RVhO
            QXhLWE9SYklQanJhZTlzRHk4WHBRT3MKLS0tIG00YWdHN3RtMkdtb2VTREljZXB3
            dXNjanh2YWpnTlBDWG9CaTdvc2dyUGcK4mnJAEpU0jZvkMKGvdMyiaEJulpVjb+w
            vo4Dqt0+lQzxSg971FLRbHj9+F/ZoVDcZ01Sbmz7LDjlyj/nrOhzVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-09T00:59:03Z"
    mac: ENC[AES256_GCM,data:z2782cm9bX6+ccaJUhl1B78tadTuO1BHQKMor32XaQBXzuONzV5jOdYFaGTCkBsSfejkGkwKcjchS8FPrSDt4vqx5c7MRNSpl2d1e0l39joZQq4WeFS+iwekDhU32UuBHCuMtKbHZQlyHSCVFP/e5m5bRLR/rk5D1vwImjDXpAU=,iv:cQqDRYjxRPDmYk4qp5qus2WwDYBESGOQyKJqXKV2W3o=,tag:PoA6rf1cMPVzGa5mhEFe1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
