---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "192.168.2.254"
  METALLB_LB_RANGE: "192.168.2.100-192.168.2.250"
  METALLB_K8S_GATEWAY_ADDR: "192.168.2.250"
  METALLB_INGRESS_ADDR: "192.168.2.249"
