---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "192.168.2.211"
  METALLB_LB_RANGE: "192.168.2.150-192.168.2.210"
  METALLB_K8S_GATEWAY_ADDR: "192.168.2.201"
  METALLB_INGRESS_ADDR: "192.168.2.202"
